template_url: 'https://raw.githubusercontent.com/meilisearch/documentation/master/.vuepress/public/sample-template.yaml'
test_files:
  - './examples/tests-suite/ruby-spec/**/*.rb'
replacers:
  - search: '@index.'
    replace: "client.index('movie')."
  - search: 'index.'
    replace: "client.index('movie')."
  - search: '@client.'
    replace: 'client.'
