name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rspec:
    name: tests
    runs-on: ubuntu-latesta

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x
    - name: Install ruby dependencies
      run: bundle install --with development
    - name: Run tests
      run: tests/run_tests.sh
    - name: Run linter
      run: bundle exec rubocop src/
